### PR TITLE
Use the google chart API instead

### PR DESCRIPTION
**Pull request by cyc**
@cedrichan 

Got a staging instance to test this on?

### CODE REVIEW

**Comment by cedrichan** [comment]
Nope. You can test it by running `/bin/hubot` locally.

**Comment by cedrichan** [comment]
chart looks busted:
chart

**Comment by cyc** [comment]
Looks like it needs the ticker to be upper-cased. Will fix.

**Comment by cyc** [comment]
YHOO

**Comment by cyc** [comment]
PTAL

**Comment by cedrichan** [comment]
:rocket: :+1: :facepunch: :ledger: :fire:

**Pull request merged**
